# Generated by Django 5.2.10 on 2026-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_convenor_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="society",
            options={
                "ordering": ["-is_featured", "-created_at"],
                "verbose_name_plural": "Societies",
            },
        ),
        migrations.AlterField(
            model_name="societymember",
            name="role",
            field=models.CharField(
                choices=[
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("secretary", "Secretary"),
                    ("convenor", "Convenor"),
                    ("treasurer", "Treasurer"),
                    ("tech_head", "Tech Head"),
                    ("creative_head", "Creative Head"),
                    ("pr_head", "PR Head"),
                    ("member", "Core Member"),
                    ("volunteer", "Volunteer"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
