# Generated by Django 5.2.10 on 2026-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_society_access_code_society_is_restricted_accesslog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_user", models.CharField(max_length=100)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("login_date", models.DateField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("device_info", models.CharField(blank=True, max_length=500)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("operating_system", models.CharField(blank=True, max_length=100)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("is_successful", models.BooleanField(default=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Admin Login Record",
                "verbose_name_plural": "Admin Login Records",
                "ordering": ["-login_time"],
            },
        ),
        migrations.AlterField(
            model_name="society",
            name="access_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
