# Generated by Django 5.2.10 on 2026-02-02 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_adminloginrecord_alter_society_access_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminuser",
            options={
                "verbose_name": "Admin User",
                "verbose_name_plural": "Admin Users",
            },
        ),
        migrations.AddField(
            model_name="adminuser",
            name="can_delete_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="can_manage_admins",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="can_manage_events",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="can_manage_societies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="can_moderate_chat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="can_view_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin - All Access"),
                    ("societies_admin", "Societies Admin - Manage Societies"),
                    ("events_admin", "Events Admin - Manage Events"),
                    ("chat_admin", "Chat Admin - Moderate Chat"),
                    ("reports_admin", "Reports Admin - View Reports"),
                    ("limited_admin", "Limited Admin - Specific Societies"),
                ],
                default="limited_admin",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AdminCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temporary_password", models.CharField(blank=True, max_length=100)),
                ("password_changed", models.BooleanField(default=False)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_token",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("token_created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="core.adminuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeveloperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("developer_id", models.CharField(max_length=50, unique=True)),
                ("master_key", models.CharField(max_length=100)),
                ("organization_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("can_create_admins", models.BooleanField(default=True)),
                ("can_delete_admins", models.BooleanField(default=True)),
                ("can_modify_permissions", models.BooleanField(default=True)),
                ("can_view_all_logs", models.BooleanField(default=True)),
                ("can_manage_all_societies", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer Admin",
                "verbose_name_plural": "Developer Admins",
            },
        ),
        migrations.CreateModel(
            name="AdminAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes_made", models.TextField(blank=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="core.adminuser",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="core.developeradmin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Access Log",
                "verbose_name_plural": "Admin Access Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="adminuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admins_created",
                to="core.developeradmin",
            ),
        ),
    ]
